Componente Upload en React
omar5876/Skill-Up-JS-Front- pull request #8
Opened 2022-11-04 20:29 UTC by Guillef33

## TICKET

Commit / 027cea745d5f88c759956b027f3de407799822ea
Ticket / https://trello.com/c/fI2XVfJx/44-28-servicio-para-subir-im%C3%A1genes
## Description
Componente del boton para agregar imagenes, con funciones onChange y onSubmit. 
Para visualizarlo, lo agregue provisoriamente a page Home.
Instale la libreria Axios, por lo que hay que volver a correr npm install.

AS: Guillermo
I Want: Iniciar proyecto y coordinar con Martin por el back
To: Martin

## Evidence:

### Happy Path
(Put screenshots/video/gifs here)

### Unhappy Path
(Put screenshots/video/gifs here)

2022-11-04 21:28 UTC, omar5876 approved these changes

2022-11-06 22:47 UTC, NachoAiup requested changes

2022-11-06 22:47 UTC, NachoAiup commented on src/Components/UploadImages/Upload.jsx
> +  function onSubmit(e) {
creo que esta funcion deberia ir en el componente contenedor, asi dependiendo el uso que le quieras dar a la imagen cargada, la agregas al formData y la mandas al endpoint requerido

2022-11-06 22:47 UTC, NachoAiup commented on src/Components/UploadImages/Upload.jsx
> +            accept="image/*"
aca creo que faltaria el error que se debe devolver si no es de la extension aceptada

2022-11-07 12:32 UTC, Guillef33 commented on src/Components/UploadImages/Upload.jsx
> +  function onSubmit(e) {
Si, puede ser, queria verlo con Martin antes. Pero de una lo tomo.

2022-11-10 14:13 UTC, NachoAiup approved these changes

2022-11-10 14:39 UTC, merged